title: Arduino IRremote
description: "Infrared remote library for Arduino: send and receive infrared signals with multiple protocols"
google_analytics: UA-60577106-2
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
